apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-agent
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
