apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-azure-kv
  namespace: ai-support-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "${KV_NAME}"
    tenantId: "${TENANT_ID}"
    objects: |
      array:
        - |
          objectName: ${SECRET_NAME_ENDPOINT}
          objectType: secret
        - |
          objectName: ${SECRET_NAME_APIKEY}
          objectType: secret
        - |
          objectName: ${SECRET_NAME_DEPLOYMENT}
          objectType: secret
  secretObjects:
    - secretName: aoai-connection
      type: Opaque
      data:
        - objectName: ${SECRET_NAME_ENDPOINT}
          key: AOAI_ENDPOINT
        - objectName: ${SECRET_NAME_APIKEY}
          key: AOAI_API_KEY
        - objectName: ${SECRET_NAME_DEPLOYMENT}
          key: AOAI_DEPLOYMENT
